# resolver: nightly-2015-08-26
# resolver: lts-8.9 
# resolver: lts-16.16
# resolver: lts-18.27
resolver: lts-20.1

allow-newer: true

flags: {}

packages:
  - '.'

extra-deps:
  - karver-0.1.2
  - hakyll-4.15.1.1
